Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/kaminari_config.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/models/operation_test.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/operation.rb'